/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    './src/pages/**/*.{ts,tsx}',
    './src/components/**/*.{ts,tsx}',
    './src/app/**/*.{ts,tsx}',
    './src/src/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "surface": "#141313",
        "on-primary-fixed": "#1a1c1c",
        "inverse-surface": "#e5e2e1",
        "surface-dim": "#141313",
        "secondary": "#adc6ff",
        "outline-variant": "#444748",
        "on-secondary-container": "#e6ecff",
        "on-tertiary-container": "#636565",
        "inverse-on-surface": "#313030",
        "tertiary": "#ffffff",
        "surface-bright": "#3a3939",
        "primary": "#ffffff",
        "surface-container-low": "#1c1b1b",
        "secondary-fixed": "#d8e2ff",
        "error-container": "#93000a",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary-fixed-variant": "#004395",
        "on-tertiary": "#2f3131",
        "background": "#141313",
        "on-surface": "#e5e2e1",
        "surface-variant": "#353434",
        "on-error-container": "#ffdad6",
        "primary-fixed-dim": "#c6c6c7",
        "surface-container-highest": "#353434",
        "on-primary": "#2f3131",
        "primary-container": "#e2e2e2",
        "on-error": "#690005",
        "on-primary-fixed-variant": "#454747",
        "on-tertiary-fixed": "#1a1c1c",
        "secondary-fixed-dim": "#adc6ff",
        "tertiary-fixed": "#e2e2e2",
        "on-secondary-fixed": "#001a42",
        "on-tertiary-fixed-variant": "#454747",
        "primary-fixed": "#e2e2e2",
        "surface-container": "#201f1f",
        "secondary-container": "#0566d9",
        "on-primary-container": "#636565",
        "on-background": "#e5e2e1",
        "surface-tint": "#c6c6c7",
        "on-surface-variant": "#c4c7c8",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-container-high": "#2a2a2a",
        "on-secondary": "#002e6a",
        "outline": "#8e9192",
        "error": "#ffb4ab",
        "inverse-primary": "#5d5f5f",
        "tertiary-container": "#e2e2e2",
        
        // Retain shadcn defaults
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      spacing: {
        "margin-mobile": "16px",
        "container-max": "1440px",
        "sidebar-width": "240px",
        "margin-desktop": "32px",
        "unit": "4px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "label-caps": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "display": ["Inter"],
        "body-lg": ["Inter"],
        "body-sm": ["Inter"],
        "label-mono": ["JetBrains Mono"]
      },
      fontSize: {
        "headline-md": ["20px", {"lineHeight": "1.4", "letterSpacing": "-0.02em", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.03em", "fontWeight": "600"}],
        "label-caps": ["11px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "display": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.04em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "label-mono": ["12px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500"}]
      }
    }
  },
  plugins: [],
}
