export enum WorkflowStepType {
  STRUCTURED_INPUT = 'STRUCTURED_INPUT',
  DOCUMENT_RETRIEVAL = 'DOCUMENT_RETRIEVAL',
  AI_EXTRACTION = 'AI_EXTRACTION',
  AI_CLASSIFICATION = 'AI_CLASSIFICATION',
  DETERMINISTIC_CONDITION = 'DETERMINISTIC_CONDITION',
  HUMAN_APPROVAL = 'HUMAN_APPROVAL',
  MOCK_EXTERNAL_ACTION = 'MOCK_EXTERNAL_ACTION',
  FINAL_REPORT = 'FINAL_REPORT',
}

export enum WorkflowStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum ExecutionStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum EventType {
  EXECUTION_STARTED = 'EXECUTION_STARTED',
  NODE_STARTED = 'NODE_STARTED',
  NODE_COMPLETED = 'NODE_COMPLETED',
  AI_REQUEST = 'AI_REQUEST',
  AI_RESPONSE = 'AI_RESPONSE',
  WAITING_FOR_APPROVAL = 'WAITING_FOR_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RETRY = 'RETRY',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
  EXECUTION_COMPLETED = 'EXECUTION_COMPLETED',
  IDEMPOTENCY_SKIP = 'IDEMPOTENCY_SKIP',
}

export enum ApprovalStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export type Position = {
  x: number;
  y: number;
};
